version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands: 
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - './*'
  name: deploy-$(date +%Y-%m-%d)
  secondary-artifacts:
    artifact1:
      base-directory: dist/client
      files:
        - './**/*'
      name: priceNinja-client-$(date +%Y-%m-%d)
    artifact2:
      base-directory: dist/server
      files:
        - './**/*'
      name: priceNinja-server-$(date +%Y-%m-%d)



